"""
Column-level 'Used for' descriptions for ERP / retail analytics schema catalog.
"""

from __future__ import annotations

import re
from typing import Dict, Optional

# Exact column name → Used for (keys are lowercase)
EXACT: Dict[str, str] = {
    # ── Branch / location ─────────────────────────────────────────────────────
    "branchalias": "Branch short name — grouping and filter in reports",
    "branchid": "Branch identifier — filter and joins",
    "branchname": "Branch full display name",
    "branchshortname": "Branch abbreviated name",
    "sourcebranchalias": "Source branch (transfer origin) — filter",
    "sourcebranchid": "Source branch ID (transfer origin)",
    "targetbranchalias": "Target branch (transfer destination) — filter",
    "targetbranchid": "Target branch ID (transfer destination)",
    "branchcity": "Branch city — geography breakdown",
    "branchstate": "Branch state — geography breakdown",
    "branchregion": "Branch region — geographic rollup",
    "branchareamanager": "Area manager responsible for branch",
    "shortname": "Short display name / alias",
    "address": "Street address line",
    "address2": "Secondary address line",
    "extaddress": "Extended address details",
    "locality": "Locality / neighborhood",
    "localitycity": "Locality city grouping",
    "localitygroup": "Locality group for regional analysis",
    "localityid": "Locality master identifier",
    "pincode": "Postal / PIN code",
    "city": "City — geography filter and breakdown",
    "state": "State — geography filter and breakdown",
    "country": "Country — geography filter",
    "countryregion": "Country / region grouping",
    "district": "District — geography breakdown",
    "iswarehouse": "Flag: branch is a warehouse location",
    # ── Department / category ───────────────────────────────────────────────────
    "department": "Department full name — hierarchy breakdown",
    "departmentname": "Department name — hierarchy breakdown",
    "departmentshortname": "Department short name — primary filter",
    "category": "Category full name — product hierarchy",
    "categoryname": "Category name — product hierarchy",
    "categoryshortname": "Category short name — primary filter",
    "subcategoryname": "Sub-category name",
    "subcategoryshortname": "Sub-category short name — filter",
    "invcategoryid": "Inventory category ID",
    "invcategoryname": "Inventory category name",
    "invcategoryshortname": "Inventory category short name",
    "invsubcategoryid": "Inventory sub-category ID",
    "invsubcategoryname": "Inventory sub-category name",
    "invsubcategoryshortname": "Inventory sub-category short name",
    "invdepartmentid": "Inventory department ID",
    "invdepartmentname": "Inventory department name",
    "invdepartmentshortname": "Inventory department short name",
    "extcategoryname": "Extended / external category label",
    # ── Supplier / vendor / party ─────────────────────────────────────────────
    "suppliername": "Supplier full name — filter and display",
    "supplieralias": "Supplier short code — filter",
    "supplieruid": "Supplier unique identifier",
    "suppliercity": "Supplier city — geography",
    "supplierstate": "Supplier state — geography",
    "partyid": "Party / vendor master ID",
    "partyname": "Party / vendor full name",
    "partyalias": "Party short alias",
    "partygroupname": "Party group classification",
    "purpartyid": "Purchase party (supplier) ID",
    "businessname": "Registered business name",
    # ── Customer ──────────────────────────────────────────────────────────────
    "customerid": "Customer identifier — filter and joins",
    "customername": "Customer full name",
    "customerfirstname": "Customer first name",
    "customerlastname": "Customer last name",
    "customertitle": "Customer title / salutation",
    "customermobilenumber": "Customer mobile phone",
    "customergroupname": "Customer group / segment",
    "contactmobile": "Contact mobile number",
    "contactemail": "Contact email address",
    "contactemail1": "Primary contact email",
    "contactemail2": "Secondary contact email",
    "contactphone1": "Primary contact phone",
    "contactphone2": "Secondary contact phone",
    "contactwebsite": "Contact website URL",
    "birthdaydt": "Customer birthday — CRM / campaigns",
    "anniversarydt": "Customer anniversary date",
    "creditlimit": "Credit limit amount",
    "creditdays": "Credit period in days",
    # ── Salesperson ───────────────────────────────────────────────────────────
    "salespersonid": "Salesperson identifier",
    "salespersonname": "Salesperson full name — Top-N and performance",
    "salespersonshortname": "Salesperson short name",
    "salespersonempid": "Salesperson employee ID",
    # ── Product / item attributes ─────────────────────────────────────────────
    "itemid": "Item / SKU identifier — joins to product master",
    "itemcode": "Item code / barcode — product lookup",
    "articleno": "Article / style number — product attribute filter",
    "articleid": "Article master identifier",
    "articleshortname": "Article short display name",
    "articlemrp": "Article-level MRP",
    "articlestocktype": "Article stock type classification",
    "sku": "Stock keeping unit code",
    "description": "Item long description",
    "extdescription": "Item extended description",
    "color": "Product color attribute — filter",
    "colour": "Product color attribute — filter",
    "colourname": "Product color display name",
    "size": "Product size attribute — filter",
    "sizename": "Product size display name",
    "contrast": "Contrast / variant attribute",
    "contrastname": "Contrast variant display name",
    "printtypework": "Print / embellishment work type",
    "printypework": "Print / embellishment work type",
    "fabric": "Primary fabric attribute",
    "subfabric": "Sub-fabric attribute",
    "fabricshortname": "Fabric short name",
    "subfabricshortname": "Sub-fabric short name",
    "property": "Product property tag (e.g. season, fit)",
    "concept": "Merchandise concept — assortment grouping",
    "collection": "Collection name — seasonal grouping",
    "dupatta": "Dupatta attribute flag / value",
    "dupattashortname": "Dupatta short name",
    "silhoutte": "Silhouette style attribute",
    "bottom": "Bottom garment type attribute",
    "neckline": "Neckline style attribute",
    "sleevetype": "Sleeve type attribute",
    "look": "Look / style tag",
    "inventorytype": "Inventory type classification",
    "para1id": "Product parameter 1 ID (variant dimension)",
    "para1name": "Product parameter 1 name (e.g. fit, style)",
    "para1shortname": "Product parameter 1 short name",
    "para2id": "Product parameter 2 ID",
    "para2name": "Product parameter 2 name",
    "para2shortname": "Product parameter 2 short name",
    "para2index": "Parameter 2 sort / variant index",
    "para3id": "Product parameter 3 ID",
    "para3name": "Product parameter 3 name",
    "para3shortname": "Product parameter 3 short name",
    "para4id": "Product parameter 4 ID",
    "para4name": "Product parameter 4 name",
    "para4shortname": "Product parameter 4 short name",
    "itemmrp": "Item maximum retail price (MRP)",
    "itemwsp": "Item wholesale price (WSP)",
    "itemexp": "Item export / extended price",
    "purchaseprice": "Item purchase / landed cost",
    "costprice": "Unit cost price",
    "mrp": "Maximum retail price",
    "hsncode": "HSN tax classification code",
    "uomid": "Unit of measure ID",
    "uomname": "Unit of measure name",
    "gstuqc": "GST unit quantity code",
    "uomtype": "Unit of measure type",
    "codingtype": "Item coding type",
    # ── Dates / periods ───────────────────────────────────────────────────────
    "xndt": "Transaction date — primary date filter for sales",
    "xndtmonth": "Transaction month label — period grouping",
    "xnmemodate": "Sales memo date — date filter",
    "xnmemodate_month": "Sales memo month (numeric) — period rollup",
    "xnmemodate_monthname": "Sales memo month name — chart axis",
    "invoicedt": "Invoice date — date filter",
    "cashmemodt": "Cash memo / bill date — date filter",
    "purdate": "Purchase date — procurement filter",
    "purinvoicedt": "Purchase invoice date",
    "purinvdt": "Purchase invoice date",
    "purchallandt": "Purchase challan date",
    "purchasedt": "Purchase transaction date",
    "purreturndt": "Purchase return date",
    "entrydt": "Stock entry date",
    "createdon": "Record created timestamp",
    "lastupdate": "Record last updated timestamp",
    "gsteffectivedt": "GST effective date",
    "msmeredt": "MSME registration date",
    "birthdaydt": "Customer birthday date",
    "anniversarydt": "Customer anniversary date",
    # ── Transaction IDs / numbers ─────────────────────────────────────────────
    "xnid": "Transaction header ID",
    "xnno": "Transaction document number",
    "xntype": "Transaction type code (sale, return, etc.)",
    "invoiceid": "Invoice header ID",
    "invoiceno": "Invoice number — document reference",
    "cashmemono": "Cash memo / bill number",
    "purchaseid": "Purchase header ID",
    "purinvoiceid": "Purchase invoice ID",
    "purinvno": "Purchase invoice number",
    "purchallanno": "Purchase challan number",
    "purreturnid": "Purchase return ID",
    "purrefno1": "Purchase reference number 1",
    "purrefno2": "Purchase reference number 2",
    # ── Quantities ────────────────────────────────────────────────────────────
    "appqty": "Application / billed quantity",
    "netslsqty": "Net sales quantity (after returns)",
    "slsqty": "Gross sales quantity",
    "slrqty": "Sales return quantity",
    "stiqty": "Stock transfer in quantity",
    "stoqty": "Stock transfer out quantity",
    "purqty": "Purchase quantity",
    "prtqty": "Purchase return quantity",
    "netpurqty": "Net purchase quantity (purchase − returns)",
    "salesquantity": "Sales quantity",
    "quantity": "Line quantity sold",
    "stockqty": "Stock on hand quantity",
    "gitqty": "Goods in transit quantity",
    # ── Amounts / values ──────────────────────────────────────────────────────
    "netamount": "Net sales amount — primary revenue metric",
    "netslsnetamount": "Net sales amount after returns — revenue KPI",
    "netamountbeforetax": "Net amount before tax",
    "salesnetamount": "Sales net amount (after discounts)",
    "salenetamount": "Sale line net amount",
    "saleamountbeforetax": "Sale amount before tax",
    "grossamount": "Gross sales amount before deductions",
    "salesprice": "Unit selling price on invoice line",
    "taxamount": "Tax amount on sale line",
    "mrpvalue": "Total MRP value",
    "costvalue": "Total cost value",
    "costprice": "Unit cost price",
    "netslscostvalue": "Net sales at cost value — margin analysis",
    "slsextcostvalue": "Sales extended cost value",
    "slscostvalue": "Sales cost value",
    "slrmrpvalue": "Sales return MRP value",
    "slrcostvalue": "Sales return cost value",
    "slrnetamount": "Sales return net amount",
    "slsmrpvalue": "Sales MRP value",
    "slsnetamount": "Sales net amount",
    "netslsmrpvalue": "Net sales MRP value",
    "purcostvalue": "Purchase cost value",
    "purnetamount": "Purchase net amount",
    "purmrpvalue": "Purchase MRP value",
    "prtcostvalue": "Purchase return cost value",
    "prtnetamount": "Purchase return net amount",
    "prtmrpvalue": "Purchase return MRP value",
    "netpurcost": "Net purchase cost",
    "netpurnetamount": "Net purchase net amount",
    "purcost": "Purchase cost amount",
    "salescost": "Sales cost (COGS) amount",
    "gitcostvalue": "Goods in transit cost value",
    "cbscostvalue": "Closing balance stock cost value",
    "cbsmrpvalue": "Closing balance stock MRP value",
    "cgstamount": "Central GST tax amount",
    "sgstamount": "State GST tax amount",
    "igstamount": "Integrated GST tax amount",
    "purcgstamount": "Purchase CGST amount",
    "pursgstamount": "Purchase SGST amount",
    "purigstamount": "Purchase IGST amount",
    "prtchgstamount": "Purchase return CGST amount",
    "prtsgstamount": "Purchase return SGST amount",
    "prtigstamount": "Purchase return IGST amount",
    "netpurcgstamount": "Net purchase CGST amount",
    "netpursgstamount": "Net purchase SGST amount",
    "netpurigstamount": "Net purchase IGST amount",
    "discountpercentage": "Discount percentage on purchases",
    "freightpercentage": "Freight charge percentage",
    "marginpercentage": "Margin percentage",
    "markupexp": "Markup on export price",
    "markupmrp": "Markup on MRP",
    "markupwsp": "Markup on wholesale price",
    "tdspercentage": "TDS deduction percentage",
    "billcount": "Number of bills / transactions — footfall KPI",
    # ── Tax / compliance ──────────────────────────────────────────────────────
    "gstclassification": "GST classification code",
    "gstclassificationstr": "GST classification description",
    "gststatecode": "GST state code",
    "taxgstinno": "GSTIN tax registration number",
    "taxpanno": "PAN tax identifier",
    "tdsid": "TDS section ID",
    "tdsname": "TDS section name",
    "tdsfullname": "TDS full description",
    # ── MSME / vendor ─────────────────────────────────────────────────────────
    "msmebiztype": "MSME business type code",
    "msmebiztypestr": "MSME business type description",
    "msmecategory": "MSME category code",
    "msmecategorystr": "MSME category description",
    "msmeredno": "MSME registration number",
    "intlglnno": "International GLN number",
    # ── Status flags ──────────────────────────────────────────────────────────
    "activestatus": "Active / inactive status flag",
    "isactive": "Active flag",
    "iswarehouse": "Warehouse location flag",
}

# View-level descriptions for non-priority objects
VIEW_DESCRIPTIONS: Dict[str, tuple[str, str]] = {
    "dbo.VW_MB_POWERBI_APR_REPORT": (
        "Application (APR) Sales Report",
        "Sales application-level transactions with branch, category, supplier, and item attributes — similar grain to APP_REPORT.",
    ),
    "dbo.VW_MB_POWERBI_BRANCH_LIST": (
        "Branch Master List",
        "Branch dimension for filters, dropdowns, and branch intelligence.",
    ),
    "dbo.VW_MB_POWERBI_CATEGORY_MASTER": (
        "Category / Department Hierarchy",
        "Inventory department, category, and sub-category master for hierarchy filters.",
    ),
    "dbo.VW_MB_POWERBI_CBS_WITH_GIT": (
        "Closing Balance Stock with GIT",
        "Stock on hand plus goods-in-transit by branch, category, and item attributes.",
    ),
    "dbo.VW_MB_POWERBI_MIS_SUPPLIER_SLS_DATA": (
        "Supplier Sales MIS",
        "Monthly supplier-wise net sales for MIS and supplier performance dashboards.",
    ),
    "dbo.VW_MB_POWERBI_PRODUCT_MASTER": (
        "Product Master",
        "Item master with department, category, supplier, fabric, and style attributes.",
    ),
    "dbo.VW_MB_POWERBI_PRT_REPORT": (
        "Purchase Return Report",
        "Purchase return transactions by branch, supplier, and item.",
    ),
    "dbo.VW_MB_POWERBI_PUR_QTY_WITH_COST": (
        "Purchase Quantity with Cost",
        "Purchase quantity and cost summary by branch, supplier, and category.",
    ),
    "dbo.VW_MB_POWERBI_PUR_REPORT": (
        "Purchase Report",
        "Purchase receipts by branch, supplier, category, and item attributes.",
    ),
    "dbo.VW_MB_POWERBI_PURXNS_REPORT": (
        "Purchase Transactions Report",
        "Detailed purchase and purchase-return transactions with tax breakdown.",
    ),
    "dbo.VW_MB_POWERBI_SLS_ARTICLE_REPORT": (
        "Sales by Article",
        "Article-level net sales and quantity for style/Article performance.",
    ),
    "dbo.VW_MB_POWERBI_SLS_BILLCOUNT": (
        "Sales Bill Count",
        "Daily bill count per branch — footfall / transaction volume KPI.",
    ),
    "dbo.VW_MB_POWERBI_SLSXNS_REPORT": (
        "Sales Transactions (SLSXNS)",
        "Sales, returns, and net sales with tax — primary transaction-level sales view.",
    ),
    "dbo.VW_MB_POWERBI_STI_REPORT": (
        "Stock Transfer In (STI)",
        "Inbound stock transfers between branches with item and value detail.",
    ),
    "dbo.VW_MB_POWERBI_STO_REPORT": (
        "Stock Transfer Out (STO)",
        "Outbound stock transfers between branches with item and value detail.",
    ),
    "dbo.VW_MB_POWERBI_STOCK_REPORT": (
        "Stock on Hand Report",
        "Current stock by branch, supplier, category, and item attributes.",
    ),
    "dbo.VW_MB_POWERBI_SUPPLIER_PUR_REPORT": (
        "Supplier Purchase Report",
        "Supplier-wise purchase history with product attributes and pricing.",
    ),
    "dbo.VW_MB_POWERBI_VENDOR_MASTER": (
        "Vendor / Party Master",
        "Supplier and vendor master with contact, tax, credit, and MSME details.",
    ),
    "dbo.VwAISalesPerson": (
        "AI Salesperson Dimension",
        "Salesperson lookup for NLQ and salesperson analytics.",
    ),
    "dbo.VwAISupplier": (
        "AI Supplier Dimension",
        "Supplier lookup for NLQ and procurement analytics.",
    ),
    "dbo.VwMstItems": (
        "Item Master View",
        "Complete item master with hierarchy, parameters, supplier, and pricing.",
    ),
}

# Regex patterns: (compiled pattern, description) — first match wins
_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"^net.*amount", re.I), "Net amount metric"),
    (re.compile(r"^gross.*amount", re.I), "Gross amount before deductions"),
    (re.compile(r"^.*cost.*value$", re.I), "Cost value amount"),
    (re.compile(r"^.*mrp.*value$", re.I), "MRP value amount"),
    (re.compile(r"^.*qty$", re.I), "Quantity metric"),
    (re.compile(r"^.*quantity$", re.I), "Quantity metric"),
    (re.compile(r"^.*count$", re.I), "Count metric"),
    (re.compile(r"^.*amount$", re.I), "Monetary amount"),
    (re.compile(r"^.*price$", re.I), "Price per unit"),
    (re.compile(r"^.*percentage$", re.I), "Percentage rate"),
    (re.compile(r"^.*dt$", re.I), "Date / timestamp — filter or grouping"),
    (re.compile(r"^.*date$", re.I), "Date — filter or grouping"),
    (re.compile(r"^.*id$", re.I), "Identifier — joins and filters"),
    (re.compile(r"^.*no$", re.I), "Document / reference number"),
    (re.compile(r"^.*name$", re.I), "Display name — filter or label"),
    (re.compile(r"^.*alias$", re.I), "Short alias — filter"),
    (re.compile(r"^.*status$", re.I), "Status flag"),
    (re.compile(r"^is.*", re.I), "Boolean flag"),
]


def describe_column(column_name: str, object_full_name: str = "") -> str:
    """Return a human-readable 'Used for' string; never returns empty or dash."""
    key = column_name.strip().lower()

    if key in EXACT:
        return EXACT[key]

    obj = object_full_name.lower()
    if "billcount" in obj and key == "billcount":
        return "Bill count per branch/day — footfall KPI"

    for pattern, desc in _PATTERNS:
        if pattern.search(column_name):
            return desc

    return f"Data field `{column_name}` — see view definition for business meaning"
